[package]
name = "amm-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float_eq = "1.0.1"
clap = { version = "4.1.8", features = ["derive"] }
thiserror = "1.0.40"
